#代理服务器监听地址
Address = 'localhost:5000'

#RPC接口行情服务器地址
RpcServer = '39.108.212.148:37011'

#TCP接口行情服务器地址
TcpServer = '39.108.212.148:37001'

#用户角色.用户ID
User = 'x.xxx'

#用户密钥
Passwd = 'xxxxxxxxxx'

#行情推送消息缓存数，默认1000
TxMsgCacheSize = 1000

#数据目录，默认./data
DataDir = './data'

#是否将行情推送消息保存到文件
EnableWriteTxMsgToFile = true

#是否将行情推送消息转换为json
EnableWriteTxMsgAsJson = true